# Generated by Django 6.0.6 on 2026-06-18 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('country_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('transitioning', 'Transitioning'), ('planned', 'Planned')], max_length=20)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('last_verified', models.DateField(auto_now=True)),
                ('source_url', models.URLField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.emergencyregion')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('number_type', models.CharField(choices=[('general', 'General'), ('police', 'Police'), ('fire', 'Fire'), ('medical', 'Medical'), ('coast', 'Coast Guard')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='api.emergencyregion')),
            ],
        ),
    ]
