# Generated by Django 6.0.6 on 2026-06-18 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencyregion',
            old_name='country_name',
            new_name='name',
        ),
    ]
