# Generated by Django 6.0.6 on 2026-06-18 05:58

from datetime import date

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

def seed_data(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    EmergencyRegion = apps.get_model('api', 'EmergencyRegion')
    EmergencyNumber = apps.get_model('api', 'EmergencyNumber')

    # --- Italia (paese base) ---
    italy = EmergencyRegion.objects.create(
        iso_code='IT',
        name='Italia',
        status='active',
        source_url='https://www.interno.gov.it'
    )
    EmergencyNumber.objects.bulk_create([
        EmergencyNumber(region=italy, number='112', number_type='general', label='NUE',                  is_primary=True),
        EmergencyNumber(region=italy, number='113', number_type='police',  label='Polizia di Stato',     is_primary=False),
        EmergencyNumber(region=italy, number='115', number_type='fire',    label='Vigili del Fuoco',     is_primary=False),
        EmergencyNumber(region=italy, number='118', number_type='medical', label='Emergenza Sanitaria',  is_primary=False),
    ])

    # --- Campania (eccezione temporanea, NUE non ancora attivo) ---
    campania_provinces = [
        ('IT-AV', 'Avellino'),
        ('IT-BN', 'Benevento'),
        ('IT-CE', 'Caserta'),
        ('IT-NA', 'Napoli'),
        ('IT-SA', 'Salerno'),
    ]
    for iso, name in campania_provinces:
        province = EmergencyRegion.objects.create(
            iso_code=iso,
            name=name,
            parent=italy,
            status='transitioning',
            valid_until=date(2026, 12, 1),  # piena operatività prevista
            source_url='https://www.interno.gov.it/it/sicurezza-nue-112-anche-campania',
        )
        EmergencyNumber.objects.bulk_create([
            EmergencyNumber(region=province, number='112', number_type='police',  label='Carabinieri',       is_primary=True),
            EmergencyNumber(region=province, number='113', number_type='police',  label='Polizia di Stato',  is_primary=False),
            EmergencyNumber(region=province, number='115', number_type='fire',    label='Vigili del Fuoco',  is_primary=False),
            EmergencyNumber(region=province, number='118', number_type='medical', label='SUEM',              is_primary=False),
        ])

    # --- Veneto (eccezione temporanea) ---
    veneto_provinces = [
        ('IT-BL', 'Belluno'),
        ('IT-PD', 'Padova'),
        ('IT-RO', 'Rovigo'),
        ('IT-TV', 'Treviso'),
        ('IT-VE', 'Venezia'),
        ('IT-VI', 'Vicenza'),
        ('IT-VR', 'Verona'),
    ]
    for iso, name in veneto_provinces:
        province = EmergencyRegion.objects.create(
            iso_code=iso,
            name=name,
            parent=italy,
            status='transitioning',
            valid_until=date(2027, 1, 1),
            source_url='https://www.regione.veneto.it',
        )
        EmergencyNumber.objects.bulk_create([
            EmergencyNumber(region=province, number='112', number_type='police',  label='Carabinieri',       is_primary=True),
            EmergencyNumber(region=province, number='113', number_type='police',  label='Polizia di Stato',  is_primary=False),
            EmergencyNumber(region=province, number='115', number_type='fire',    label='Vigili del Fuoco',  is_primary=False),
            EmergencyNumber(region=province, number='118', number_type='medical', label='SUEM 118',          is_primary=False),
        ])


def unseed_data(apps: StateApps, schema_editor) -> None:
    EmergencyRegion = apps.get_model('api', 'EmergencyRegion')
    EmergencyRegion.objects.filter(iso_code__startswith='IT').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_country_name_emergencyregion_name'),
    ]


    operations = [
        migrations.RunPython(seed_data, unseed_data),
    ]
