# Generated by Django 6.0.6 on 2026-06-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_seed_emergency_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyregion',
            name='iso_code',
            field=models.CharField(db_index=True, max_length=6, unique=True),
        ),
    ]
